### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by rupalchawla** [g-loot/react-tournament-brackets#51]
Thanks for the repo, I am trying to use it but getting below error, do you know what might be causing it?

index.js?46cb:598 Uncaught ReferenceError: window is not defined
    at Object.<anonymous> (file:///Users/user/proj/test/node_modules/@g-loot/react-tournament-brackets/dist/bundle.js:1:390)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.@g-loot/react-tournament-brackets (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:692:18)
    at __webpack_require__ (file:///Users/user/proj/test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/component/event/draws/SESinglesBracket.tsx:8:91)
    at Object../src/component/event/draws/SESinglesBracket.tsx (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:319:1)
    at __webpack_require__ (file:///Users/user/proj/test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/event/[evtId]/EventHomePage.tsx:45:100)
    at Function.__webpack_require__.a (file:///Users/user/proj/test/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/pages/event/[evtId]/EventHomePage.tsx:1:21)
    at Object../src/pages/event/[evtId]/EventHomePage.tsx (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:660:1)
    at __webpack_require__ (file:///Users/user/proj/test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/event/[evtId]/index.tsx:6:74)
    at Function.__webpack_require__.a (file:///Users/user/proj/test/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/pages/event/[evtId]/index.tsx:1:21)
    at Object../src/pages/event/[evtId]/index.tsx (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:671:1)
    at __webpack_require__ (file:///Users/user/proj/test/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:1692:39)
    at <unknown> (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:1693:28)
    at Object.<anonymous> (file:///Users/user/proj/test/.next/server/pages/event/[evtId].js:1696:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (file:///Users/user/proj/test/node_modules/next/dist/server/require.js:88:12)
    at <unknown> (file:///Users/user/proj/test/node_modules/next/dist/server/load-components.js:49:73)
    at async Object.loadComponentsImpl [as loadComponents] (file:///Users/user/proj/test/node_modules/next/dist/server/load-components.js:49:26)
    at async DevServer.findPageComponentsImpl (file:///Users/user/proj/test/node_modules/next/dist/server/next-server.js:600:36)

**Comment by erwinespl** [comment]
on nextjs ? follow this thread : https://github.com/g-loot/react-tournament-brackets/issues/34

**Comment by Shenato** [comment]
Please let me know if this change fixes it https://github.com/g-loot/react-tournament-brackets/pull/64

You can easily test it by npm installing this beta release https://www.npmjs.com/package/@g-loot/react-tournament-brackets/v/1.0.31-rc
